'use strict';
console.log('hello, world');
const $h1 = document.querySelector('h1');
console.dir($h1);
const $explanation = document.querySelector('#explanation');
console.dir($explanation);
const $hint = document.querySelector('.hint');
console.dir($hint);
const $pNodeList = document.querySelectorAll('p');
console.dir($pNodeList);
const $exampleLinkClassNodeList = document.querySelectorAll('.example-link');
console.dir($exampleLinkClassNodeList);
